from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
WORKSPACE_DIR = BASE_DIR.parent
DATA_DIR = BASE_DIR / "data"
GRAPH_DIR = BASE_DIR / "graph"
OUTPUT_DIR = BASE_DIR / "outputs"
SOURCE_LIBRARY_DIR = WORKSPACE_DIR / "调规知识问答"
SOURCE_PLAN_DIR = SOURCE_LIBRARY_DIR / "知识库pdf" / "预案调规文档"
SOURCE_REGULATION_DIR = SOURCE_LIBRARY_DIR / "运行规定库"
BGE_M3_MODEL_DIR = WORKSPACE_DIR / "bge-m3"
RAG_INDEX_DIR = OUTPUT_DIR / "rag_index"
RAG_CHUNKS_JSONL = RAG_INDEX_DIR / "chunks.jsonl"
RAG_DENSE_NPY = RAG_INDEX_DIR / "dense.npy"
RAG_MANIFEST_JSON = RAG_INDEX_DIR / "manifest.json"

LLM_BASE_URL = "http://202.117.43.44:8848/v1"
LLM_API_KEY = "EMPTY"
LLM_MODEL = "Qwen3.5-4B"
LLM_TIMEOUT_SECONDS = 60
