package org.example.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import io.milvus.client.MilvusServiceClient;
import io.milvus.param.R;
import io.milvus.param.collection.HasCollectionParam;
import org.example.constant.MilvusConstants;
import org.example.entity.KnowledgeChunk;
import org.example.entity.KnowledgeDocument;
import org.example.entity.KnowledgeProcessTask;
import org.example.mapper.KnowledgeChunkMapper;
import org.example.mapper.KnowledgeDocumentMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class RagDiagnosticsService {

    private static final long EMBEDDING_HEALTH_CACHE_MS = 60_000L;

    @Autowired
    private KnowledgeDocumentMapper documentMapper;

    @Autowired
    private KnowledgeChunkMapper chunkMapper;

    @Autowired
    private KnowledgeBaseService knowledgeBaseService;

    @Autowired
    private VectorEmbeddingService embeddingService;

    @Autowired(required = false)
    private MilvusServiceClient milvusClient;

    @Value("${milvus.enabled:false}")
    private boolean milvusEnabled;

    private volatile Map<String, Object> cachedEmbeddingStatus;
    private volatile long cachedEmbeddingStatusAt;

    public Map<String, Object> health() {
        Map<String, Object> report = new LinkedHashMap<>();
        Map<String, Object> milvus = milvusStatus();
        report.put("checkedAt", LocalDateTime.now().toString());
        report.put("mysql", mysqlStatus());
        report.put("milvus", milvus);
        report.put("embeddingApi", cachedEmbeddingStatus());
        report.put("storage", storageStatus(milvus));
        report.put("counts", counts());
        return report;
    }

    public Map<String, Object> selfTest() {
        Map<String, Object> report = new LinkedHashMap<>();
        long started = System.currentTimeMillis();
        String marker = "GRIDOPS_RAG_SELFTEST_" + Long.toHexString(started);
        String content = "RAG self test document " + marker
                + ". Transformer oil temperature alarm: check load, current, cooler, oil pump, fan and alarm history.";
        String query = marker + " transformer oil temperature cooler alarm history";
        String documentId = null;

        try {
            KnowledgeDocument document = knowledgeBaseService.uploadDocument(
                    new TextMultipartFile("rag-self-test.md", content),
                    "RAG_SELF_TEST",
                    "rag-self-test",
                    "Temporary document generated by RAG self test",
                    "self-test,rag");
            documentId = document.getDocumentId();

            Map<String, Object> waitResult = waitForProcessing(documentId, 25_000L);
            report.put("processing", displayProcessing(waitResult));

            List<VectorSearchService.SearchResult> results = knowledgeBaseService.searchTest(query, 5);
            String selfTestDocumentId = documentId;
            boolean matched = results.stream().anyMatch(r -> contains(r.getMetadata(), selfTestDocumentId));
            report.put("retrievalMatched", matched);
            report.put("retrievalCount", results.size());

            report.put("status", matched ? "PASS" : "WARN");
            report.put("message", matched
                    ? "上传、索引与检索链路正常"
                    : "上传与索引完成，但检索未命中自检文档");
        } catch (Exception e) {
            report.put("status", "FAIL");
            report.put("message", e.getMessage());
        } finally {
            if (documentId != null) {
                try {
                    report.put("cleanup", knowledgeBaseService.deleteDocument(documentId) ? "DELETED" : "NOT_FOUND");
                } catch (Exception e) {
                    report.put("cleanup", "FAILED: " + e.getMessage());
                }
            }
            report.put("durationMs", System.currentTimeMillis() - started);
        }
        return report;
    }

    private Map<String, Object> displayProcessing(Map<String, Object> processing) {
        Map<String, Object> display = new LinkedHashMap<>();
        display.put("documentStatus", processing.get("documentStatus"));
        display.put("chunkCount", processing.get("chunkCount"));
        display.put("embeddingCount", processing.get("embeddingCount"));
        display.put("taskStatus", processing.get("taskStatus"));
        display.put("currentStep", processing.get("currentStep"));
        Object errorMessage = processing.get("errorMessage");
        if (errorMessage != null) {
            display.put("errorMessage", errorMessage);
        }
        return display;
    }

    private Map<String, Object> cachedEmbeddingStatus() {
        long now = System.currentTimeMillis();
        Map<String, Object> cached = cachedEmbeddingStatus;
        if (cached != null && now - cachedEmbeddingStatusAt < EMBEDDING_HEALTH_CACHE_MS) {
            Map<String, Object> copy = new LinkedHashMap<>(cached);
            copy.put("cached", true);
            return copy;
        }
        Map<String, Object> fresh = embeddingService.checkRemoteEmbeddingApi();
        cachedEmbeddingStatus = fresh;
        cachedEmbeddingStatusAt = now;
        return fresh;
    }

    private Map<String, Object> mysqlStatus() {
        Map<String, Object> status = new LinkedHashMap<>();
        try {
            documentMapper.selectCount(null);
            status.put("status", "UP");
            status.put("message", "Knowledge tables are reachable");
        } catch (Exception e) {
            status.put("status", "DOWN");
            status.put("message", e.getMessage());
        }
        return status;
    }

    private Map<String, Object> milvusStatus() {
        Map<String, Object> status = new LinkedHashMap<>();
        status.put("enabled", milvusEnabled);
        status.put("collection", MilvusConstants.MILVUS_COLLECTION_NAME);

        if (!milvusEnabled || milvusClient == null) {
            status.put("status", "DOWN");
            status.put("message", "Milvus is unavailable; using in-memory vector store. Data will be lost after restart.");
            return status;
        }

        try {
            R<Boolean> response = milvusClient.hasCollection(HasCollectionParam.newBuilder()
                    .withCollectionName(MilvusConstants.MILVUS_COLLECTION_NAME)
                    .build());
            boolean exists = response.getStatus() == 0 && Boolean.TRUE.equals(response.getData());
            status.put("status", exists ? "UP" : "DOWN");
            status.put("message", exists ? "Collection is available" : "Collection is missing: " + response.getMessage());
        } catch (Exception e) {
            status.put("status", "DOWN");
            status.put("message", e.getMessage());
        }
        return status;
    }

    private Map<String, Object> storageStatus(Map<String, Object> milvusStatus) {
        Map<String, Object> storage = new LinkedHashMap<>();
        boolean usingMilvus = milvusEnabled && milvusClient != null && "UP".equals(milvusStatus.get("status"));
        storage.put("mode", usingMilvus ? "MILVUS" : "MEMORY");
        storage.put("persistent", usingMilvus);
        storage.put("warning", usingMilvus ? null : "当前使用内存向量库，重启会丢失。");
        return storage;
    }

    private Map<String, Object> counts() {
        Map<String, Object> counts = new LinkedHashMap<>();
        List<KnowledgeDocument> enabledDocuments = documentMapper.selectList(
                new LambdaQueryWrapper<KnowledgeDocument>().eq(KnowledgeDocument::getEnabled, 1));
        List<String> enabledDocumentIds = enabledDocuments.stream()
                .map(KnowledgeDocument::getDocumentId)
                .toList();
        counts.put("documents", enabledDocuments.size());
        counts.put("chunks", enabledDocumentIds.isEmpty()
                ? 0
                : chunkMapper.selectCount(new LambdaQueryWrapper<KnowledgeChunk>()
                        .eq(KnowledgeChunk::getStatus, "ACTIVE")
                        .in(KnowledgeChunk::getDocumentId, enabledDocumentIds)));
        counts.put("vectors", enabledDocuments.stream()
                .map(KnowledgeDocument::getEmbeddingCount)
                .filter(v -> v != null)
                .mapToInt(Integer::intValue)
                .sum());
        return counts;
    }

    private Map<String, Object> waitForProcessing(String documentId, long timeoutMs) throws InterruptedException {
        long deadline = System.currentTimeMillis() + timeoutMs;
        KnowledgeDocument document;
        KnowledgeProcessTask task = null;
        do {
            document = knowledgeBaseService.getDocument(documentId);
            task = knowledgeBaseService.getProcessStatus(documentId);
            String status = document != null ? document.getStatus() : null;
            if ("COMPLETED".equals(status) || "PARTIAL_COMPLETED".equals(status) || "FAILED".equals(status)) {
                return processSnapshot(document, task);
            }
            Thread.sleep(500L);
        } while (System.currentTimeMillis() < deadline);

        Map<String, Object> timeout = processSnapshot(knowledgeBaseService.getDocument(documentId), task);
        timeout.put("timedOut", true);
        return timeout;
    }

    private Map<String, Object> processSnapshot(KnowledgeDocument document, KnowledgeProcessTask task) {
        Map<String, Object> snapshot = new LinkedHashMap<>();
        if (document != null) {
            snapshot.put("documentStatus", document.getStatus());
            snapshot.put("chunkCount", document.getChunkCount());
            snapshot.put("embeddingCount", document.getEmbeddingCount());
        }
        if (task != null) {
            snapshot.put("taskStatus", task.getStatus());
            snapshot.put("currentStep", task.getCurrentStep());
            snapshot.put("errorMessage", task.getErrorMessage());
        }
        return snapshot;
    }

    private boolean contains(String value, String needle) {
        return value != null && needle != null && value.contains(needle);
    }

    private static class TextMultipartFile implements MultipartFile {
        private final String filename;
        private final byte[] content;

        private TextMultipartFile(String filename, String content) {
            this.filename = filename;
            this.content = content.getBytes(StandardCharsets.UTF_8);
        }

        @Override
        public String getName() {
            return "file";
        }

        @Override
        public String getOriginalFilename() {
            return filename;
        }

        @Override
        public String getContentType() {
            return "text/markdown";
        }

        @Override
        public boolean isEmpty() {
            return content.length == 0;
        }

        @Override
        public long getSize() {
            return content.length;
        }

        @Override
        public byte[] getBytes() {
            return content.clone();
        }

        @Override
        public InputStream getInputStream() {
            return new ByteArrayInputStream(content);
        }

        @Override
        public void transferTo(java.io.File dest) throws IOException {
            java.nio.file.Files.write(dest.toPath(), content);
        }
    }
}
